version: '3.8'

services:
    app:
        container_name: node-sequelize-api
        user: 'node'
        restart: unless-stopped
        command: 'npm run start'
        ports:
            - 3000:3000
        volumes:
            - ./:/home/node/app
        working_dir: /home/node/app
        image: node:17.2.0-alpine